### ISSUE TITLE
panic: runtime error

### ISSUE THREAD

**Issue by ring04h** [praetorian-inc/fingerprintx#22]
./fingerprintx -t 1.12.227.111:22

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x1004fae9c]

goroutine 1 [running]:
github.com/praetorian-inc/fingerprintx/pkg/plugins/services/ssh.(*SSHPlugin).Run(0x1400000e010?, {0x1006fce00?, 0x1400000e010}, 0x1006fce00?, {{{{0x0, 0xffff010ce36f}, 0x140001160c0}, 0x16}, {0x0, 0x0}})
	/home/runner/work/fingerprintx/fingerprintx/pkg/plugins/services/ssh/ssh.go:267 +0x71c
github.com/praetorian-inc/fingerprintx/pkg/scan.simplePluginRunner({0x1006fce00?, 0x1400000e010?}, {{{{0x0, 0xffff010ce36f}, 0x140001160c0}, 0x16}, {0x0, 0x0}}, 0x1400109fd40, {0x1006fb720?, ...})
	/home/runner/work/fingerprintx/fingerprintx/pkg/scan/simple_scan.go:195 +0x160
github.com/praetorian-inc/fingerprintx/pkg/scan.(*Config).SimpleScanTarget(0x1400109fd40, {{{{0x0, 0xffff010ce36f}, 0x140001160c0}, 0x16}, {0x0, 0x0}})
	/home/runner/work/fingerprintx/fingerprintx/pkg/scan/simple_scan.go:106 +0x694
github.com/praetorian-inc/fingerprintx/pkg/scan.ScanTargets({0x1400111d680?, 0x1, 0x0?}, {0x0, 0x0, 0x77359400, 0x0})
	/home/runner/work/fingerprintx/fingerprintx/pkg/scan/scan_api.go:47 +0x10c
github.com/praetorian-inc/fingerprintx/pkg/runner.glob..func1(0x100945020?, {0x100554e4d?, 0x2?, 0x2?})
	/home/runner/work/fingerprintx/fingerprintx/pkg/runner/root.go:44 +0x100
github.com/spf13/cobra.(*Command).execute(0x100945020, {0x1400010e190, 0x2, 0x2})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x4d0
github.com/spf13/cobra.(*Command).ExecuteC(0x100945020)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/praetorian-inc/fingerprintx/pkg/runner.Execute()
	/home/runner/work/fingerprintx/fingerprintx/pkg/runner/root.go:80 +0x28
main.main()
	/home/runner/work/fingerprintx/fingerprintx/cmd/fingerprintx/fingerprintx.go:22 +0x1c
```

**Comment by praetorian-thendrickson** [comment]
Hey @ring04h, thanks for the interest in our project. If you rebuild off main (with this commit https://github.com/praetorian-inc/fingerprintx/commit/bef637e04ed7e887ab5c9772ebbcfa5d2b1603b6), I think that will fix the issue.
